### ISSUE TITLE
新增 点击区域消失 我可以提交吗

### ISSUE THREAD

**Issue by wuyajun7** [yilylong/HighLight-UserGuideView#1]
新增 点击区域（全部|terget区域）消失 我可以提交吗

**Comment by yilylong** [comment]
可以，不过我记得是做了点击区域消失吧，记不清了

发自网易邮箱 iPhone 版
在2016年05月18日 18:28，Peter 写道:

新增 点击区域（全部|terget区域）消失 我可以提交吗

**Comment by wuyajun7** [comment]
是的，你做的是点击任何位置都可以消失，我这边有需求点击高亮位置消失，我就增加了这个处理

**Comment by wuyajun7** [comment]
o no，我没有权限

**Comment by yilylong** [comment]
你可以提交pull request
