### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by freetuyue** [yilylong/HighLight-UserGuideView#2]
为什么高亮的地方有一些误差，还有就是高亮有一些延迟

**Comment by yilylong** [comment]
能说下在哪些情况下吗 误差是高度上的话可能是状态栏计算错误

**Comment by freetuyue** [comment]
是整体向下偏移了位置。后来我注释了一些代码，没有偏移的情况了，但是高亮的蒙版有延迟

来自 魅族 MX2

-------- 原始邮件 --------
发件人：hailongzhao notifications@github.com
时间：周三 5月25日 16:51
收件人：yilylong/UserGuideView UserGuideView@noreply.github.com
抄送：freetuyue meiyoulezxh@sina.com,Author author@noreply.github.com
主题：Re: [yilylong/UserGuideView] 小问题 (#2)

**Comment by yilylong** [comment]
也可能跟你的style有关 有statubar 和 无statubar的情况 可以使用setStatubar()调节
