### ISSUE TITLE
东西很不错 但是没有实际运用不太友好

### ISSUE THREAD

**Issue by iflyman** [yilylong/HighLight-UserGuideView#8]
1.没法一个个指示 显示顺序
2.设置是传一张图片，应该支持view，可以自定义view传入
3.按照demo调了下，指针的指向，还有圈的大小都不太准确，比如说，写一行文字，setHeightView之后，并没有完全圈中文字，且指针，方向也不可调。
不过仍旧感谢，如果以上问题都解决，是一个相当不错的控件，可以生存在大多app中。最后再次感谢。

**Comment by yilylong** [comment]
请使用V1.0.1
